### ISSUE TITLE
Changing profession does not change trades

### ISSUE THREAD

**Issue by smmmadden** [AlessioDP/SecurityVillagers#1]
Hi - I just started testing this resource with 1.13 and have v2.9.0 on a Spigot 1.13 server.  I was able to rename one of the villagers and change a profession from Cleric to Farmer and the villager changed appearance correctly.  Unfortunately, the trades associated with the Cleric did not change to the expected trades of a Farmer.  I didn't find any help on our wiki that gets into any details for the commands or trades, so posting the issue here.  Thanks! -Steve

**Comment by AlessioDP** [comment]
I've made some tests:
If you change the profession of a villager, you will change its carreer too, but items won't change. (Thats normal)

Right now SecurityVillagers doesn't support items changing, but I will try to figure out if there is a good an simple way to do that. For now, you cannot change trade items with this plugin :S
