### ISSUE TITLE
Excepetion thrown

### ISSUE THREAD

**Issue by omegadmm** [AlessioDP/SecurityVillagers#2]
![capture](https://user-images.githubusercontent.com/24850883/50719443-7dcd7600-1061-11e9-95fb-ad6c46e27d66.PNG)
Got this exception when dropping in the plugin.

**Comment by smmmadden** [comment]
there is a problem with his website updater not the plugin itself.  I started getting the same thing today too on my PaperSpigot Server.

**Comment by omegadmm** [comment]
Good to know! Ty

**Comment by AlessioDP** [comment]
Sorry for the inconvenience, yesterday I've updated the website and I didn't fixed a problem with the subdomain used to check for updates. Now it should works :)
